name : Github Akash Action No.2

on:
  push:
    branches: ["main"]

jobs:
   build:
      run-on: ubuntu-latest
      steps:
         - name: CheckOut
           uses: actions/checkout@v3
         - name: Setup Node
           uses: actios/setup-node@v3
           with:
              node-version: "16"
         - name: Install Dependencies
           run: npm ci
         - name: Build Project
           run: npm run build
            
          